language: java
jdk:
  - oraclejdk8
#  - oraclejdk7
#  - openjdk6
install: 
  - ant
before_script: 
  - cd bin
  - chmod 755 bamqc
script: 
  - java -classpath junit-4.11.jar:hamcrest-core-1.3.jar:log4j-1.2.16.jar:sam-1.103.jar:commons-math3-3.5.jar:commons-lang3-3.4.jar:. org.junit.runner.JUnitCore test.java.uk.ac.babraham.BamQC.Modules.AllTests
  - ./bamqc --version
